### ISSUE TITLE
Considered Switching Containers?

### ISSUE THREAD

**Issue by CozMedic** [mbierman/unifi-installer-for-Firewalla#4]
Hi there,

Very much appreciate your scripts and documentation to make this setup a breeze. I just wanted to ask if you have considered switching/testing an alternate container for the Unifi controller instead of Jacobalberty's, as it seems possible that it will no longer be updated. He seems to be the only one with write access to the repo and has been 'MIA'. Others have seemingly opened their own PR's or forks to keep the controller up to date.

Thanks,

**Comment by mbierman** [comment]
Hi I'd consider it. Looking at Jacobalberty's distro, it was last updated two months ago. There are 72 contributors.  I would only consider running a distro that seems really solid. That means testing unifi's release, checking dependencies, and only then releasing.  I don't see another distro that looks promising. Do you have any specific recommendations to look at?

**Comment by CozMedic** [comment]
Hi, thanks for the response. I’m personally favored toward linuxserver/unifi-network-application as I use their images for just about everything without issue, however, this image in particular requires MongoDB (which they also provide). This is also the case for most, like another popular one (goofball222/unifi), because they’re based on Alpine. The plus side being that they’re smaller images.

I have a pretty… un-serious setup at home, I’d be happy to test & see if it can be a drop-in replacement or not and open a PR with an updated compose file.
