### ISSUE TITLE
Networks configured - No such file or directory

### ISSUE THREAD

**Issue by randallzapata** [mbierman/unifi-installer-for-Firewalla#6]
I just ran this for the first time on my firewalla, and I got this issue. Everything is working, but wanted you to know.

Networks configured
bash: line 67: /root/.firewalla/config/dnsmasq_local/unifi: No such file or directory

**Comment by randallzapata** [comment]
I think it should be /home/pi/.firewalla/config/dnsmasq_local/unifi

**Comment by mbierman** [comment]
Fixed.
